name: Basic Python CI

on:
  push:
    branches:
      - dev
      - feature/ci-pipeline

jobs:
  run-python-script:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show runner information
        run: |
          echo "Current directory:"
          pwd
          echo "Files in repo:"
          ls -la
          echo "Python version:"
          python --version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run validation script
        run: python validate.py